### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by Hans0924** [ReactivePlatform/netty-in-action-cn#18]
首先还是感谢译者引进了netty in action这本好书，但是在阅读过程中，有一些语句翻译得不够明白，要反复读上好多遍才能明白要表达的含义，举几个例子：

> The movement of an event through the pipeline is the work of the ChannelHandlers that have been installed during the initialization, or bootstrapping phase of the application. (3.2.2)
> 使得事件流经 ChannelPipeline 是 ChannelHandler 的工作，它们是在应用程序的初始化或者引导阶段被安装的。

「使得事件流经 ChannelPipeline 是 ChannelHandler 的工作」虽然勉勉强强能读懂，但是翻译成「ChannelHandler 的作用是让事件在 ChannelPipeline 中传递」一眼就能看明白。

> These internal details of NIO are hidden by the user-level API common to all of Netty’s transport implementations. （4.3.1）
> 对于所有 Netty 的传输实现都共有的用户级别 API 完全地隐藏了这些 NIO 的内部细节。

这里要表达的主要意思应该是「API隐藏了内部细节」，然而译文表达出了「对API隐藏了内部细节」的意思，这里的「对于」影响了语义。

又如：

> Invoked when ChannelnboundHandler.fireUserEventTriggered() is called because a POJO was passed through the ChannelPipeline. (table 6.3)
> 当 ChannelnboundHandler.fireUserEventTriggered()方法被调用时被调用，因为一个 POJO 被传经了 ChannelPipeline

后半句的「被传经了」简直就是按字直译，有点怀疑是机器翻译的结果，翻译成「因为POJO是通过ChannelPipeline传递的」都比生造一个莫名的词要好。

翻译工作是非常辛苦的，但是书中出现的许多翻译上的瑕疵是通读一遍就能发现的，不知是不是编辑催稿的缘故，译者没有来得及仔细思考，给人一种仓促间逐词直译的感受。

**Comment by He-Pin** [comment]
>「使得事件流经 ChannelPipeline 是 ChannelHandler 的工作」虽然勉勉强强能读懂，但是翻译成「ChannelHandler 的作用是让事件在 ChannelPipeline 中传递」一眼就能看明白。
改译下也可以。

>这里要表达的主要意思应该是「API隐藏了内部细节」，然而译文表达出了「对API隐藏了内部细节」的意思，这里的「对于」影响了语义。

这里是不对的，这里是说的 这些API 隐藏了细节，这些API对于所有的用户级别的传输实现共有，这句话唯一的问题是应该拆句。

>后半句的「被传经了」简直就是按字直译，有点怀疑是机器翻译的结果，翻译成「因为POJO是通过ChannelPipeline传递的」都比生造一个莫名的词要好。

这里不太对吧，这里改译的意思倒是不差，可是把被动改为主动，只是从侧面刻画了而已。本质上是调用者调用ChannelPipeline的方法来传递的，可不是ChannelPipeline自己传递的。

**Comment by He-Pin** [comment]
@Hans0924 部分地方可以改译，您看的是最新的电子版本吗？但是有些地方可能不能采取您的那种译法。
