### ISSUE TITLE
求解答netty websocket方面的问题

### ISSUE THREAD

**Issue by Alyson12345** [ReactivePlatform/netty-in-action-cn#22]
你好，我最近在求客户端（js写的）大并发提交数据到java服务器端的程序，想在js和java之间做一个缓冲池。我用的是netty-socket.io实现数据传到java程序存到缓冲队列当中当中。由于我不太了解netty，想问一下netty-socket.io能否保证大并发数据的不丢失?
如果这种方法不行，那我应该怎么做?

**Comment by He-Pin** [comment]
不丢。。。。不可能啊，业务层都需要自己保证的，你可以采用下Play啊这些框架来，比较简单。
@Alyson12345 .
