### ISSUE TITLE
签售相关

### ISSUE THREAD

**Issue by He-Pin** [ReactivePlatform/netty-in-action-cn#3]
已经完结

**Comment by binbinyouliiii** [comment]
上海市宝山区月浦镇盛桥月狮五队曹家宅 曹海宁 13061755847  支付宝订单20170514200040011100670011984905 ID:lord

**Comment by He-Pin** [comment]
@binbinyouliiii 谢谢哈，我后面发货了给你说，差点吓死我了，收到了没人留言这个页面。

**Comment by He-Pin** [comment]
签售已经完结，再进行了哈。谢谢各位支持。
