### ISSUE TITLE
关于decode调用描述与官方不符

### ISSUE THREAD

**Issue by wuwenbin555** [ReactivePlatform/netty-in-action-cn#30]
书中126页，表格中关于decode方法的描述：对于此方法的调用，将会重复进行，直到确定没有新的元素被添加到该List。
我在官方文档（https://netty.io/wiki/user-guide-for-4.x.html#wiki-h2-3）中看到的描述是：
decode() can decide to add nothing to out where there is not enough data in the cumulative buffer. ByteToMessageDecoder will call decode() again when there is more data received.
我理解这句英文的意思是：如果没有内容添加至out（也就是您书中的List）时，说明可能存在粘包的情况，没有接收到完整的数据，所以需要再继续调用decode，将完整的数据包全部收到，然后再放入out中， 而您书中的意思是没有元素添加到List，则中止调用decode，意思刚好相反了，您觉得呢？

**Comment by He-Pin** [comment]
不对，是一直解析，有数据就添加到out List，解析不到数据就算了。跳出了。你看下源码？
