### ISSUE TITLE
第34页，“可以”格式有误

### ISSUE THREAD

**Issue by CFM880** [ReactivePlatform/netty-in-action-cn#5]
在第34页，3.2.2小节，最后一段，如下着重处（PS:只知道PDF版是这样的）

在Netty中，有两种发送消息的方式。 你可以直接写到Channel中，也`可以`写到和ChannelHandler 相关的ChannelHandlerContext 对象中。

**Comment by He-Pin** [comment]
@CFM880 您好，不好意思，这个我在书中没有看到呢，我也对照了英文版没有特殊处理。

您可以加 QQ群：221092326

感谢

**Comment by CFM880** [comment]
嗯嗯，应该是我PDF阅读器的问题
