### ISSUE TITLE
页#147, 表11-3

### ISSUE THREAD

**Issue by chainkite** [ReactivePlatform/netty-in-action-cn#6]
页#147, 表11-3, 第三行:
数据帧: 属于上一个BinaryWebSocketFrame或者TextWebSocketFrame的文本的或者二进制数据

这里BinaryXxx和TextXxx的顺序最好与后面中文的顺序一致吧

**Comment by He-Pin** [comment]
ContinuationWebSocketFrame Data frame: text or binary data that belongs to a previous
BinaryWebSocketFrame or TextWebSocketFrame

@chainkite 原文是这个，您的意思是？

**Comment by He-Pin** [comment]
我明白了，你说的对，谢谢哦，调整下更好。您可以加一下QQ群：221092326 哦，谢谢了。

**Comment by He-Pin** [comment]
http://www.epubit.com.cn/book/details/4228
